X = input("What is your Favorite color?: ")
print("your favorite color is " + X)
Y = input("Why do you like the color " + X + "?")
print("Thats cool that you like the color " + X + " becase of " + Y)
Z = input ("What is your least favorite color?: ")
print ("oh, " + Z + " is a bad color.")
A = input ("Why do you not like " + Z + "?: ")
print ("that make's sense, for why you don't like " + Z)
print ("I hope that you have a GREAT DAY!!!")