print("-------------------------------------------")
fname = input("What is your First Name? ")
lname = input("What is your Last Name? ")
email = input("What is your E-mail? ")
phonenum = input("What is your phone number? ")
jobtitle = input("What is your job title? ")
id_num = input("What is your id number? ")
print("-------------------------------------------")
print("The ID card is: ")
print("-------------------------------------------")
print(lname.upper() + " , " + fname.capitalize())
print(jobtitle.title())
print("ID: " + id_num)
print("")
print(email)
print(phonenum)
print("-------------------------------------------")
